"""initial schema

Revision ID: be6073f3677c
Revises: 
Create Date: 2026-10-04 12:15:09.544506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401  (autogenerate renders VECTOR columns with this path)
import fastapi_users_db_sqlalchemy.generics  # noqa: F401  (renders the GUID type of users/oauth_accounts)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be6073f3677c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must be installed on the server. Creating the extension needs a superuser
    # the first time; if this fails, run `CREATE EXTENSION vector;` in the database as postgres.
    # downgrade() leaves the extension in place because other schemas may use it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts'))
    )
    op.create_index(op.f('ix_oauth_accounts_account_id'), 'oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_oauth_name'), 'oauth_accounts', ['oauth_name'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('personal', 'organization')", name=op.f('ck_workspaces_kind')),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 120', name=op.f('ck_workspaces_name_length')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('created_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_cases_priority')),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'closed', 'archived')", name=op.f('ck_cases_status')),
    sa.CheckConstraint('length(title) BETWEEN 1 AND 200', name=op.f('ck_cases_title_length')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cases_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_cases_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index('ix_cases_workspace_status', 'cases', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_cases_workspace_reference', 'cases', ['workspace_id', 'reference_code'], unique=True, postgresql_where=sa.text('reference_code IS NOT NULL'))
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name=op.f('ck_workspace_members_role')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_members'))
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_audit_events_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_case_created', 'audit_events', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_workspace_created', 'audit_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('case_index_meta',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('raptor_root_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hippo_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_index_meta_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_case_index_meta'))
    )
    op.create_table('case_members',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('lead', 'investigator', 'viewer')", name=op.f('ck_case_members_role')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_case_members_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_members_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_case_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'user_id', name=op.f('pk_case_members'))
    )
    op.create_index(op.f('ix_case_members_user_id'), 'case_members', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('top_k', sa.SmallInteger(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('graphrag', 'raptor', 'hippo', 'hybrid')", name=op.f('ck_chat_messages_method')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_chat_messages_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_case_created', 'chat_messages', ['case_id', 'created_at'], unique=False)
    op.create_table('communities',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_communities_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'community_id', name=op.f('pk_communities'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=255), server_default='', nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('indexing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'indexing', 'indexed', 'error')", name=op.f('ck_documents_status')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_documents_size_nonneg')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_documents_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index('ix_documents_case_sha', 'documents', ['case_id', 'sha256'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('community', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('PERSON', 'ORGANIZATION', 'LOCATION', 'DATE', 'EVENT', 'CONCEPT', 'PRODUCT', 'LAW', 'DISEASE', 'DRUG', 'OTHER')", name=op.f('ck_entities_type')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_entities_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('case_id', 'normalized_key', name=op.f('uq_entities_case_id_normalized_key')),
    sa.UniqueConstraint('case_id', 'seq', name=op.f('uq_entities_case_id_seq'))
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_table('hippo_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('child_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('chunk_idx', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_hippo_nodes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hippo_nodes')),
    sa.UniqueConstraint('case_id', 'seq', name=op.f('uq_hippo_nodes_case_id_seq'))
    )
    op.create_index(op.f('ix_hippo_nodes_case_id'), 'hippo_nodes', ['case_id'], unique=False)
    op.create_table('raptor_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('children', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('doc_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_raptor_nodes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raptor_nodes')),
    sa.UniqueConstraint('case_id', 'seq', name=op.f('uq_raptor_nodes_case_id_seq'))
    )
    op.create_index(op.f('ix_raptor_nodes_case_id'), 'raptor_nodes', ['case_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_chunks_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name=op.f('uq_chunks_document_id_chunk_index'))
    )
    op.create_index(op.f('ix_chunks_case_id'), 'chunks', ['case_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_mentions_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'chunk_id', name=op.f('pk_entity_mentions'))
    )
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_relationships_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_relationships_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_relationships_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('case_id', 'seq', name=op.f('uq_relationships_case_id_seq'))
    )
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_chunks_case_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_raptor_nodes_case_id'), table_name='raptor_nodes')
    op.drop_table('raptor_nodes')
    op.drop_index(op.f('ix_hippo_nodes_case_id'), table_name='hippo_nodes')
    op.drop_table('hippo_nodes')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_documents_case_sha', table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('communities')
    op.drop_index('ix_chat_messages_case_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_case_members_user_id'), table_name='case_members')
    op.drop_table('case_members')
    op.drop_table('case_index_meta')
    op.drop_index('ix_audit_events_workspace_created', table_name='audit_events')
    op.drop_index('ix_audit_events_case_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('uq_cases_workspace_reference', table_name='cases', postgresql_where=sa.text('reference_code IS NOT NULL'))
    op.drop_index('ix_cases_workspace_status', table_name='cases')
    op.drop_table('cases')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_oauth_name'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_account_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
